version: '3.8'
services:
  db:
    image: mariadb:latest
    container_name: db-wp-photos
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file: .env
    restart: always
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp-photos
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html/
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'      
      WORDPRESS_TABLE_PREFIX: wp_
volumes:
  db_data:
